server:
  port: 84

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false # 개발시에는 false로(default: true)

openapi:
  serviceKey: ${SERVICE_KEY}
  baseUrl: ${URL}